version: "3.9"
services:
  pg:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: secretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init-volume:/docker-entrypoint-initdb.d
      - ./data-volume:/var/lib/postgresql/data
  pg-admin:
    image: "dpage/pgadmin4"
    ports:
      - "4444:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@pg.pg
      PGADMIN_DEFAULT_PASSWORD: secretpassword
      PGADMIN_DISABLE_POSTFIX: true
    volumes:
      - ./user-volume:/opt/
      - ./config-volume:/var/lib/pgadmin
    depends_on:
      - pg
  adminer:
    image: adminer
    depends_on:
      - pg
    ports:
      - 5555:8080  
